"""add_networth_snapshots

Revision ID: 06fbae7d8e34
Revises: 3c917b71a1cf
Create Date: 2026-03-29 22:10:36.523769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fbae7d8e34'
down_revision: Union[str, Sequence[str], None] = '3c917b71a1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networth_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_month', sa.String(length=7), nullable=False),
    sa.Column('total_networth', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_month', name='uq_user_snapshot_month')
    )
    op.create_index(op.f('ix_networth_snapshots_user_id'), 'networth_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_networth_snapshots_user_id'), table_name='networth_snapshots')
    op.drop_table('networth_snapshots')
    # ### end Alembic commands ###
