"""add_asset_investment_transaction_asset_price

Revision ID: 1cb0c99972e7
Revises: 4ecc3e4c64e0
Create Date: 2026-03-25 15:58:38.547169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb0c99972e7'
down_revision: Union[str, Sequence[str], None] = '4ecc3e4c64e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('asset_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_asset_prices_asset_date')
    )
    op.create_index(op.f('ix_asset_prices_asset_id'), 'asset_prices', ['asset_id'], unique=False)
    op.create_table('investment_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fees', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investment_transactions_account_date', 'investment_transactions', ['account_id', 'date'], unique=False)
    op.create_index('ix_investment_transactions_asset_date', 'investment_transactions', ['asset_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_investment_transactions_asset_date', table_name='investment_transactions')
    op.drop_index('ix_investment_transactions_account_date', table_name='investment_transactions')
    op.drop_table('investment_transactions')
    op.drop_index(op.f('ix_asset_prices_asset_id'), table_name='asset_prices')
    op.drop_table('asset_prices')
    op.drop_table('assets')
    # ### end Alembic commands ###
