"""add_source_to_networth_snapshots

Revision ID: 24ac8c1c9554
Revises: b2c3d4e5f6a7
Create Date: 2026-03-30 16:35:13.108256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ac8c1c9554'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networth_snapshots', sa.Column('source', sa.String(length=10), nullable=False, server_default='auto'))
    op.create_index('ix_networth_snapshots_user_source', 'networth_snapshots', ['user_id', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_networth_snapshots_user_source', table_name='networth_snapshots')
    op.drop_column('networth_snapshots', 'source')
    # ### end Alembic commands ###
