"""add_exchange_rate

Revision ID: d7baca819772
Revises: e7273aa2edbd
Create Date: 2026-03-25 16:13:20.929198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7baca819772'
down_revision: Union[str, Sequence[str], None] = 'e7273aa2edbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'target_currency', 'date', name='uq_exchange_rates_base_target_date')
    )
    op.create_index(op.f('ix_exchange_rates_base_currency'), 'exchange_rates', ['base_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_target_currency'), 'exchange_rates', ['target_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_target_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_base_currency'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
