"""add_budget_models

Revision ID: e7273aa2edbd
Revises: 1cb0c99972e7
Create Date: 2026-03-25 16:06:17.446195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7273aa2edbd'
down_revision: Union[str, Sequence[str], None] = '1cb0c99972e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('delimiter', sa.String(length=1), nullable=False),
    sa.Column('date_column', sa.String(length=50), nullable=False),
    sa.Column('amount_column', sa.String(length=50), nullable=False),
    sa.Column('description_column', sa.String(length=50), nullable=False),
    sa.Column('reference_column', sa.String(length=50), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('encoding', sa.String(length=20), nullable=False),
    sa.Column('skip_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_profiles_user_id'), 'bank_profiles', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('monthly_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_categories_user_name')
    )
    op.create_index('ix_categories_user_archived', 'categories', ['user_id', 'is_archived'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('income_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_sources_user_year_month', 'income_sources', ['user_id', 'year', 'month'], unique=False)
    op.create_table('auto_cat_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_cat_rules_category_id'), 'auto_cat_rules', ['category_id'], unique=False)
    op.create_table('statement_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('bank_profile_id', sa.String(length=36), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_profile_id'], ['bank_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_statement_imports_user_uploaded', 'statement_imports', ['user_id', 'uploaded_at'], unique=False)
    op.create_table('budget_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('is_investment', sa.Boolean(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['statement_imports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budget_transactions_dedup_hash', 'budget_transactions', ['dedup_hash'], unique=False)
    op.create_index('ix_budget_transactions_user_category', 'budget_transactions', ['user_id', 'category_id'], unique=False)
    op.create_index('ix_budget_transactions_user_date', 'budget_transactions', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budget_transactions_user_date', table_name='budget_transactions')
    op.drop_index('ix_budget_transactions_user_category', table_name='budget_transactions')
    op.drop_index('ix_budget_transactions_dedup_hash', table_name='budget_transactions')
    op.drop_table('budget_transactions')
    op.drop_index('ix_statement_imports_user_uploaded', table_name='statement_imports')
    op.drop_table('statement_imports')
    op.drop_index(op.f('ix_auto_cat_rules_category_id'), table_name='auto_cat_rules')
    op.drop_table('auto_cat_rules')
    op.drop_index('ix_income_sources_user_year_month', table_name='income_sources')
    op.drop_table('income_sources')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index('ix_categories_user_archived', table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_bank_profiles_user_id'), table_name='bank_profiles')
    op.drop_table('bank_profiles')
    # ### end Alembic commands ###
