"""add source field to statement_import

Revision ID: ebf846aa0baf
Revises: d7baca819772
Create Date: 2026-03-27 14:07:03.338402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf846aa0baf'
down_revision: Union[str, Sequence[str], None] = 'd7baca819772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statement_imports', sa.Column('source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statement_imports', 'source')
    # ### end Alembic commands ###
